---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ CI_PROJECT_NAME }}
  name: {{ CI_PROJECT_NAME }}
  namespace: {{ CI_PROJECT_NAMESPACE }}-{{ CI_ENVIRONMENT_SLUG }}
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
    - port: 80
      targetPort: 5000 
      protocol: TCP
  selector:
    run: {{ CI_PROJECT_NAME }} 
    track: stable
  type: NodePort
  sessionAffinity: ClientIP
