---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ CI_PROJECT_NAME }}-{{ TRACK|default('stable', true) }}
  namespace: {{ CI_PROJECT_NAMESPACE }}-{{ CI_ENVIRONMENT_SLUG }}
spec:
  replicas: {{ REPLICAS|default(1, true) }}
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: {{ CI_PROJECT_NAME }}
        track: {{ TRACK|default('stable', true) }}
    spec:
      imagePullSecrets:
        - name: ecregistry
      containers:
        - name: {{ CI_PROJECT_NAME }}
          image: ecregistry.azurecr.io/{{ CI_PROJECT_NAMESPACE }}/{{ CI_PROJECT_NAME }}:{{ DOCKER_IMAGE_TAG }}
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "500M"
              cpu: 1
            limits:
              memory: "1000M"
              cpu: 1