apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ CI_PROJECT_NAME }}
  namespace: {{ CI_PROJECT_NAMESPACE }}-{{ CI_ENVIRONMENT_SLUG }}
  annotations:
   kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ ingress.server_name }}
    secretName: {{ CI_PROJECT_NAME }}-tls
  rules:
  - host: {{ ingress.server_name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ CI_PROJECT_NAME }}
          servicePort: 80
